### ISSUE TITLE
Rework client name fields (nickname INT vs EXT)

### ISSUE THREAD

**Issue by christophpickl** [christophpickl/gadsu#119]
split nickname into A) internal nickname (displayed in app) and B) external nickname (used in mails). current nickname is equal to internal nickname.

## TODOs

* [x] rename current nickname to "internal nickname" (DB changes)
* [x] add new field "external nickname" (model, DB, UI)
* [x] check what "preferred name" is good for => for internal AND external ATM; change for mail
* [x] adapt mail template filling
